package Mps_Practice.behavior;

/*Generated by MPS */


public class ItemList_BehaviorDescriptor extends Section_BehaviorDescriptor {
  public ItemList_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Mps_Practice.structure.ItemList";
  }
}
