package Mps_Practice.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Item_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Item_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Mps_Practice.structure.Item";
  }
}
