package Mps_Practice.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Section_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Section_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Mps_Practice.structure.Section";
  }
}
